In [68]:
import torch
import numpy as np
import pandas as pd
import sklearn
import matplotlib.pyplot as plt

## Here is my first neural network.

The interface for the neural network is simple: it accepts an input variable as information and a weights variable as knowledge, and it outputs a prediction.

In [69]:
weight = 0.1
number_of_toes = [8.5, 9.5, 10, 9]
x = number_of_toes[0]

def neural_network(x, weight):
    pred = x * weight
    return pred

In [70]:
prediction = neural_network(x, weight)
print('prediction: %.2f' % prediction)

prediction: 0.85


## Making a prediction with multiple inputs

In [71]:
# Performing a weighted sum of inputs
def w_sum(a, b):
    assert(len(a) == len(b))
    output = 0.0
    for i in range(len(a)):
        output += (a[i] * b[i])
    return output

In [72]:
weights = [0.1, 0.2, 0]

# This new neural network can accept multiple inputs at a time per prediction.
# This allows the network to combine various forms of information to make better-informed decisions.
# But the fundamental mechanism for using weights hasn’t changed.
# You still take each input and run it through its own volume knob.
# In other words, you multiply each input by its own weight.
def neural_network(x, weights):
    pred = w_sum(x, weights)
    return pred

toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

x = [toes[0], wlrec[0], nfans[0]]
pred = neural_network(x, weights)
print('%.2f' % pred)

0.98


The new property here is that, because you have multiple inputs, you have to sum their respective predictions. Thus, you multiply each input by its respective weight and then sum all the local predictions together. This is called a weighted sum of the input, or a weighted sum for short. Some also refer to the weighted sum as a dot product, as you’ll see.

## Vector math

In [73]:
def elementwise_multiplication(vec_a,vec_b):
    assert(len(vec_a) == len(vec_b))
    
    out = []
    for i in range(len(vec_a)):
        out.append(vec_a[i] * vec_b[i])
    return out

def elementwise_addition(vec_a,vec_b):
    assert(len(vec_a) == len(vec_b))
    
    out = []
    for i in range(len(vec_a)):
        out.append(vec_a[i] + vec_b[i])
    return out


def vector_sum(vec_a):
    _sum = 0.0
    for i in range(len(vec_a)):
        _sum += vec_a[i]
    return _sum

def vector_average(vec_a):
    return vector_sum(vec_a) / len(vec_a)

In [74]:
a = [1,2,3]
b = [3,2,1]

In [75]:
out = elementwise_multiplication(a, b)
print(out)

[3, 4, 3]


In [76]:
elementwise_addition(a, b)

[4, 4, 4]

In [77]:
vector_sum(a)

6.0

In [78]:
vector_average(a)

2.0

In [79]:
def weighted_sum(a, b):
    mul = elementwise_multiplication(a, b)
    return vector_sum(mul)

def neural_network(x, weights):
    pred = weighted_sum(x, weights)
    return pred

In [80]:
pred = neural_network(x, weights)
print('prediction: %.2f' % pred)

prediction: 0.98


In [87]:
import numpy as np

weights = np.array([0.1, 0.2, 0])

def neural_network(_input, weights):
    pred = _input.dot(weights)
    return pred

toes = np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65, 0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])

_input = np.array([toes[0],wlrec[0],nfans[0]])
pred = neural_network(_input,weights)
print('%.2f' % pred)

0.98


## Predicting with multiple inputs and outputs

In [102]:
def vect_mat_mul(vect, matrix):
    assert(len(vect) == len(matrix))
    output = [0,0,0]
    
    for i in range(len(vect)):
        output[i] = w_sum(vect, matrix[i])
    return output

In [110]:
weights = [
    [0.1, 0.1, -0.3], # hurt?
    [0.1, 0.2, 0.0], # win?
    [0.0, 1.3, 0.1], # sad?
]

def neural_network(x, weights):
    pred = vect_mat_mul(x, weights)
    return pred


In [113]:
toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65,0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

X = [
    [8.5, 9.5, 9.9, 9.0],
    [0.65,0.8, 0.8, 0.9],
    [1.2, 1.3, 0.5, 1.0],
]

In [116]:
x = [toes[0],wlrec[0],nfans[0]]
pred = neural_network(x,weights)
print(pred)

[0.555, 0.9800000000000001, 0.9650000000000001]


In [117]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [119]:
np.random.rand(3,5)

array([[0.59539652, 0.27958925, 0.24344361, 0.90818161, 0.02105386],
       [0.75896852, 0.35818034, 0.61384386, 0.64397423, 0.47899265],
       [0.97450413, 0.53146345, 0.76227619, 0.30887943, 0.93707496]])

In [120]:
a = np.zeros((1,4))
b = np.zeros((4,3))

In [121]:
a

array([[0., 0., 0., 0.]])

In [122]:
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [123]:
c = a.dot(b)

In [124]:
c

array([[0., 0., 0.]])

In [125]:
c.shape

(1, 3)